package otserver4s.game

import otserver4s.{ Client, Packet }

object PacketInGame {

  def manterConexaoAtiva(client: Client): Unit = {
    val teste =
      !client.socket.isClosed &&
      client.socket.getInputStream.available > 0
    if(teste) {
      val tamanhoPacket = Packet.lerInt16(client.socket.getInputStream) 
      for(i <- 0 until tamanhoPacket)
        print(s"${Packet.lerByte(client.socket.getInputStream)}, ")
      println("\nOk")
    }
    manterConexaoAtiva(client)
  }
  
  def iniciarConexaoAtiva(client: Client): Packet = {
    val packet = Packet()
    /*
    client.jogador.map(jogador => {
      Conectados.adicionar(client)
      var pular = -1
      def descricaoChao(x: Int, y: Int, z: Int,
            comp: Short, alt: Short, offset: Int) = {
        for (nx <- 0 until comp) for (ny <- 0 until alt) {
          val posicaoCalculo = Posicao(
            (x + nx + offset).toShort,
            (y + ny + offset).toShort,
            (z & 0xff).toByte)
          Option(Mapa.getPiso(posicaoCalculo)) match {
            case Some(piso) => {
              if (pular > -1) {
                packet.escreverByte((pular & 0xff).toByte)
                packet.escreverByte(0xff.toByte)
              }
              pular = 0
              client.jogador.filter(_.posicao() == posicaoCalculo).map(jg => {
                packet.escreverInt16(0x61)
                packet.escreverInt32(0x00)
                packet.escreverInt32(jg.idInGame)
                packet.escreverString(jg.nome)
                
                packet.escreverByte(100)
                packet.escreverByte(jg.direcao().codigo)
                
                packet.escreverByte(jg.tipoOutfit)
                packet.escreverByte(jg.cabecaOutfit)
                packet.escreverByte(jg.corpoOutfit)
                packet.escreverByte(jg.pernasOutfit)
                packet.escreverByte(jg.pesOutfit)
                
                packet.escreverByte(jg.luz.raio)
                packet.escreverByte(jg.luz.cor)
                packet.escreverInt16(20)
                packet.escreverByte(jg._caveira)
                packet.escreverByte(jg.escudo.codigo)
              })
            }
            case None => {
              pular += 1
              if (pular == 0xff) {
                packet.escreverByte(0xff.toByte)
                packet.escreverByte(0xff.toByte)
                pular = -1
              }
            }
          }
        }
      }
      def descricaoMapa(x: Int, y: Int, z: Byte, 
          comp: Short, alt: Short) = {
        var inicioZ = 7
        var fimZ = 0
        var passoZ = -1
        if(z > 7) {
          inicioZ = z - 2
          fimZ = Math.min(15, z + 2)
          passoZ = 1
        }
        var nz = inicioZ
        while(nz != fimZ + passoZ) {
          descricaoChao(x, y, nz, comp, alt, z - nz)
          nz += passoZ
        }
        if(pular > -1) {
          packet.escreverByte((pular & 0xff).toByte)
          packet.escreverByte(0xff.toByte)
        }
      }
      packet.escreverByte(Packet.CODIGO_PACKET_PROCESSAR_LOGIN_SUCESSO)
      packet.escreverInt32(jogador.idInGame)
      packet.escreverInt16(0x32) // Velocidade de renderização do client
      packet.escreverByte(0x01) // Pode reportar erros
      
      packet.escreverByte(0x64) // Adicionar descricao do mapa
      packet.escreverInt16(jogador.posicaox)
      packet.escreverInt16(jogador.posicaoy)
      packet.escreverByte(jogador.posicaoz)
      descricaoMapa(
        jogador.posicaox - 8, jogador.posicaoy - 6, 
        jogador.posicaoz, 18, 14)
      
      Slot.values.foreach(slot => {
        packet.escreverByte(0x79)
        packet.escreverByte(slot.codigo)
      })
      
      packet.escreverByte(0xa0.toByte)
      packet.escreverInt16(jogador.vida)
      packet.escreverInt16(jogador.vidaMaxima)
      packet.escreverInt16(jogador.capacidade)
      packet.escreverInt32(jogador.exp)
      packet.escreverInt16(1) // Level
      packet.escreverByte(0) // % Level
      packet.escreverInt16(jogador.mana)
      packet.escreverInt16(jogador.manaMaxima)
      packet.escreverByte(jogador.magicLevel)
      packet.escreverByte(0) // % ML
      packet.escreverByte(jogador.alma)
      
      packet.escreverByte(0xa1.toByte)
      packet.escreverByte(jogador.fistLevel)
      packet.escreverByte(0x00)
      packet.escreverByte(jogador.clubLevel)
      packet.escreverByte(0x00)
      packet.escreverByte(jogador.swordLevel)
      packet.escreverByte(0x00)
      packet.escreverByte(jogador.axeLevel)
      packet.escreverByte(0x00)
      packet.escreverByte(jogador.distanceLevel)
      packet.escreverByte(0x00)
      packet.escreverByte(jogador.shieldLevel)
      packet.escreverByte(0x00)
      packet.escreverByte(jogador.fishingLevel)
      packet.escreverByte(0x00)
      
      packet.escreverByte(0x83.toByte)
      packet.escreverInt16(jogador.posicaox)
      packet.escreverInt16(jogador.posicaoy)
      packet.escreverByte(jogador.posicaoz)
      packet.escreverByte(0x04)
      
      packet.escreverByte(0x82.toByte)
      packet.escreverByte(jogador.luz.raio)
      packet.escreverByte(jogador.luz.cor)
    })
    */
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((16 & 0xff).toByte)
    packet.escreverByte((50 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((1 & 0xff).toByte)
    packet.escreverByte((100 & 0xff).toByte)
    packet.escreverByte((50 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((50 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((7 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((97 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((16 & 0xff).toByte)
    packet.escreverByte((4 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((77 & 0xff).toByte)
    packet.escreverByte((97 & 0xff).toByte)
    packet.escreverByte((105 & 0xff).toByte)
    packet.escreverByte((97 & 0xff).toByte)
    packet.escreverByte((100 & 0xff).toByte)
    packet.escreverByte((2 & 0xff).toByte)
    packet.escreverByte((128 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((20 & 0xff).toByte)
    packet.escreverByte((30 & 0xff).toByte)
    packet.escreverByte((40 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((106 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((228 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((1 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((2 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((3 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((4 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((5 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((6 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((7 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((8 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((9 & 0xff).toByte)
    packet.escreverByte((121 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((160 & 0xff).toByte)
    packet.escreverByte((150 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((150 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((144 & 0xff).toByte)
    packet.escreverByte((1 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((1 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((100 & 0xff).toByte)
    packet.escreverByte((161 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((10 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((131 & 0xff).toByte)
    packet.escreverByte((50 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((50 & 0xff).toByte)
    packet.escreverByte((0 & 0xff).toByte)
    packet.escreverByte((7 & 0xff).toByte)
    packet.escreverByte((4 & 0xff).toByte)
    packet.escreverByte((130 & 0xff).toByte)
    packet.escreverByte((255 & 0xff).toByte)
    packet.escreverByte((215 & 0xff).toByte)
    packet
  }
  
}
